# Generated by Django 3.2.15 on 2022-10-06 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile', models.ImageField(null=True, upload_to='Creatorprofile')),
                ('address', models.TextField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FeMale', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('coverphoto', models.ImageField(blank=True, null=True, upload_to='Creatorprofile')),
                ('city', models.CharField(choices=[('Andaman and Nicobar Islands', (('Port Blair', 'Port Blair'),)), ('Andhra Pradesh', (('Visakhapatnam', 'Visakhapatnam'), ('Vijayawada', 'Vijayawada'), ('Guntur', 'Guntur'), ('Nellore', 'Nellore'), ('Kurnool', 'Kurnool'), ('Rajamahendravaram', 'Rajamahendravaram'), ('Tirupati', 'Tirupati'), ('Kadapa', 'Kadapa'), ('Kakinada', 'Kakinada'), ('Anantapur', 'Anantapur'), ('Vizianagaram', 'Vizianagaram'), ('Eluru', 'Eluru'), ('Ongole', 'Ongole'), ('Nandyal', 'Nandyal'), ('Machilipatnam', 'Machilipatnam'), ('Adoni', 'Adoni'), ('Tenali', 'Tenali'), ('Proddatur', 'Proddatur'), ('Chittoor', 'Chittoor'), ('Hindupur', 'Hindupur'), ('Bhimavaram', 'Bhimavaram'), ('Madanapalle', 'Madanapalle'), ('Guntakal', 'Guntakal'), ('Srikakulam', 'Srikakulam'), ('Dharmavaram', 'Dharmavaram'), ('Gudivada', 'Gudivada'), ('Narasaraopet', 'Narasaraopet'), ('Tadipatri', 'Tadipatri'), ('Tadepalligudem', 'Tadepalligudem'), ('Amaravati', 'Amaravati'), ('Chilakaluripet', 'Chilakaluripet'))), ('Bihar', (('Patna', 'Patna'), ('Gaya', 'Gaya'), ('Bhagalpur', 'Bhagalpur'), ('Muzaffarpur', 'Muzaffarpur'), ('Purnia', 'Purnia'), ('Darbhanga', 'Darbhanga'), ('Bihar Sharif', 'Bihar Sharif'), ('Arrah', 'Arrah'), ('Begusarai', 'Begusarai'), ('Katihar', 'Katihar'), ('Munger', 'Munger'), ('Chhapra', 'Chhapra'), ('Bettiah', 'Bettiah'), ('Saharsa', 'Saharsa'), ('Hajipur', 'Hajipur'), ('Sasaram', 'Sasaram'), ('Dehri', 'Dehri'), ('Siwan', 'Siwan'), ('Motihari', 'Motihari'), ('Nawada', 'Nawada'), ('Bagaha', 'Bagaha'), ('Buxar', 'Buxar'), ('Kishanganj', 'Kishanganj'), ('Sitamarhi', 'Sitamarhi'), ('Jamalpur', 'Jamalpur'), ('Jehanabad', 'Jehanabad'), ('Aurangabad', 'Aurangabad'), ('Lakhisarai', 'Lakhisarai'))), ('Chandigarh', (('Chandigarh', 'Chandigarh'),)), ('Chhattisgarh', (('Raipur', 'Raipur'), ('Durg', 'Durg'), ('Naya Raipur', 'Naya Raipur'), ('Korba', 'Korba'), ('Bilaspur', 'Bilaspur'), ('Rajnandgaon', 'Rajnandgaon'), ('Pakhanjore', 'Pakhanjore'), ('Jagdalpur', 'Jagdalpur'), ('Ambikapur', 'Ambikapur'), ('Chirmiri', 'Chirmiri'), ('Dhamtari', 'Dhamtari'), ('Raigarh', 'Raigarh'), ('Mahasamund', 'Mahasamund'))), ('Daman and Diu', (('Daman', 'Daman'),)), ('Delhi', (('Delhi', 'Delhi'),)), ('Dadra and Nagar Haveli', (('Silvassa', 'Silvassa'),)), ('Goa', (('Panaji', 'Panaji'), ('Vasco', 'Vasco'), ('Mormugao', 'Mormugao'), ('Margao', 'Margao'))), ('Gujarat', (('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Vadodara', 'Vadodara'), ('Rajkot', 'Rajkot'), ('Bhavnagar', 'Bhavnagar'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Gandhidham', 'Gandhidham'), ('Nadiad', 'Nadiad'), ('Gandhinagar', 'Gandhinagar'), ('Anand', 'Anand'), ('Morbi', 'Morbi'), ('Khambhat', 'Khambhat'), ('Surendranagar', 'Surendranagar'), ('Bharuch', 'Bharuch'), ('Vapi', 'Vapi'), ('Navsari', 'Navsari'), ('Veraval', 'Veraval'), ('Porbandar', 'Porbandar'), ('Godhra', 'Godhra'), ('Bhuj', 'Bhuj'), ('Ankleshwar', 'Ankleshwar'), ('Botad', 'Botad'), ('Patan', 'Patan'), ('Palanpur', 'Palanpur'), ('Dahod', 'Dahod'), ('Jetpur', 'Jetpur'), ('Valsad', 'Valsad'), ('Kalol', 'Kalol'), ('Gondal', 'Gondal'), ('Deesa', 'Deesa'), ('Amreli', 'Amreli'), ('Amreli', 'Amreli'), ('Mahuva', 'Mahuva'), ('Mehsana', 'Mehsana'))), ('Himachal Pradesh', (('Shimla', 'Shimla'),)), ('Haryana', (('Faridabad', 'Faridabad'), ('Gurgaon', 'Gurgaon'), ('Panipat', 'Panipat'), ('Ambala', 'Ambala'), ('Yamunanagar', 'Yamunanagar'), ('Rohtak', 'Rohtak'), ('Hisar', 'Hisar'), ('Karnal', 'Karnal'), ('Sonipat', 'Sonipat'), ('Panchkula', 'Panchkula'), ('Bhiwani', 'Bhiwani'), ('Sirsa', 'Sirsa'), ('Bahadurgarh', 'Bahadurgarh'), ('Jind', 'Jind'), ('Thanesar', 'Thanesar'), ('Kaithal', 'Kaithal'), ('Rewari', 'Rewari'), ('Palwal', 'Palwal'))), ('Jharkhand', (('Jamshedpur', 'Jamshedpur'), ('Dhanbad', 'Dhanbad'), ('Ranchi', 'Ranchi'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Deoghar', 'Deoghar'), ('Phusro', 'Phusro'), ('Hazaribagh', 'Hazaribagh'), ('Giridih', 'Giridih'), ('Ramgarh', 'Ramgarh'), ('Medininagar', 'Medininagar'), ('Chirkunda', 'Chirkunda'), ('Jhumri Telaiya', 'Jhumri Telaiya'), ('Sahibganj', 'Sahibganj'))), ('Jammu and Kashmir', (('Srinagar', 'Srinagar'), ('Jammu', 'Jammu'), ('Anantnag', 'Anantnag'))), ('Karnataka', (('Bengaluru', 'Bengaluru'), ('Hubli', 'Hubli'), ('Mysore', 'Mysore'), ('Gulbarga', 'Gulbarga'), ('Mangalore', 'Mangalore'), ('Belgaum', 'Belgaum'), ('Davangere', 'Davangere'), ('Bellary', 'Bellary'), ('Bijapur', 'Bijapur'), ('Shimoga', 'Shimoga'), ('Tumkur', 'Tumkur'), ('Raichur', 'Raichur'), ('Bidar', 'Bidar'), ('Hospet', 'Hospet'), ('Hassan', 'Hassan'), ('Gadag', 'Gadag'), ('Udupi', 'Udupi'), ('Robertsonpet', 'Robertsonpet'), ('Bhadravati', 'Bhadravati'), ('Chitradurga', 'Chitradurga'), ('Harihar', 'Harihar'), ('Kolar', 'Kolar'), ('Mandya', 'Mandya'), ('Chikkamagallooru', 'Chikkamagallooru'), ('Chikmagalur', 'Chikmagalur'), ('Gangawati', 'Gangawati'), ('Ranebennuru', 'Ranebennuru'), ('Ramanagara', 'Ramanagara'), ('Bagalkot', 'Bagalkot'))), ('Kerala', (('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kochi', 'Kochi'), ('Calicut', 'Calicut'), ('Kollam', 'Kollam'), ('Thrissur', 'Thrissur'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Alappuzha', 'Alappuzha'), ('Alappuzha', 'Alappuzha'), ('Palakkad', 'Palakkad'), ('Kottayam', 'Kottayam'), ('Kothamangalam', 'Kothamangalam'), ('Malappuram', 'Malappuram'), ('Manjeri', 'Manjeri'), ('Thalassery', 'Thalassery'), ('Ponnani', 'Ponnani'))), ('Lakshadweep', (('Kavaratti', 'Kavaratti'),)), ('Maharashtra', (('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Aurangabad', 'Aurangabad'), ('Solapur', 'Solapur'), ('Bhiwandi', 'Bhiwandi'), ('Amravati', 'Amravati'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Sangli-Miraj-Kupwad', 'Sangli-Miraj-Kupwad'), ('Jalgaon', 'Jalgaon'), ('Akola', 'Akola'), ('Latur', 'Latur'), ('Malegaon', 'Malegaon'), ('Dhule', 'Dhule'), ('Ahmednagar', 'Ahmednagar'), ('Nandurbar', 'Nandurbar'), ('Ichalkaranji', 'Ichalkaranji'), ('Chandrapur', 'Chandrapur'), ('Jalna', 'Jalna'), ('Parbhani', 'Parbhani'), ('Bhusawal', 'Bhusawal'), ('Satara', 'Satara'), ('Beed', 'Beed'), ('Pandharpur', 'Pandharpur'), ('Yavatmal', 'Yavatmal'), ('Kamptee', 'Kamptee'), ('Gondia', 'Gondia'), ('Achalpur', 'Achalpur'), ('Osmanabad', 'Osmanabad'), ('Hinganghat', 'Hinganghat'), ('Wardha', 'Wardha'), ('Barshi', 'Barshi'), ('Chalisgaon', 'Chalisgaon'), ('Amalner', 'Amalner'), ('Khamgaon', 'Khamgaon'), ('Akot', 'Akot'), ('Udgir', 'Udgir'), ('Bhandara', 'Bhandara'), ('Parli', 'Parli'))), ('Meghalaya', (('Shillong', 'Shillong'),)), ('Manipur', (('Imphal', 'Imphal'),)), ('Madhya Pradesh', (('Indore', 'Indore'), ('Bhopal', 'Bhopal'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Ujjain', 'Ujjain'), ('Sagar', 'Sagar'), ('Dewas', 'Dewas'), ('Satna', 'Satna'), ('Ratlam', 'Ratlam'), ('Rewa', 'Rewa'), ('Katni', 'Katni'), ('Singrauli', 'Singrauli'), ('Burhanpur', 'Burhanpur'), ('Khandwa', 'Khandwa'), ('Morena', 'Morena'), ('Bhind', 'Bhind'), ('Chhindwara', 'Chhindwara'), ('Guna', 'Guna'), ('Shivpuri', 'Shivpuri'), ('Vidisha', 'Vidisha'), ('Chhatarpur', 'Chhatarpur'), ('Damoh', 'Damoh'), ('Mandsaur', 'Mandsaur'), ('Khargone', 'Khargone'), ('Neemuch', 'Neemuch'), ('Pithampur', 'Pithampur'), ('Hoshangabad', 'Hoshangabad'), ('Itarsi', 'Itarsi'), ('Sehore', 'Sehore'), ('Betul', 'Betul'), ('Seoni', 'Seoni'), ('Datia', 'Datia'), ('Nagda', 'Nagda'), ('Dhanpuri', 'Dhanpuri'), ('Dhar', 'Dhar'), ('Balaghat', 'Balaghat'))), ('Mizoram', (('Aizawl', 'Aizawl'),)), ('Nagaland', (('Dimapur', 'Dimapur'), ('Kohima', 'Kohima'))), ('Odisha', (('Bhubaneswar', 'Bhubaneswar'), ('Cuttack', 'Cuttack'), ('Rourkela', 'Rourkela'), ('Berhampur', 'Berhampur'), ('Sambalpur', 'Sambalpur'), ('Puri', 'Puri'), ('Balasore', 'Balasore'), ('Bhadrak', 'Bhadrak'), ('Baripada', 'Baripada'), ('Balangir', 'Balangir'), ('Jharsuguda', 'Jharsuguda'), ('Jeypore', 'Jeypore'))), ('Punjab', (('Ludhiana', 'Ludhiana'), ('Amritsar', 'Amritsar'), ('Jalandhar', 'Jalandhar'), ('Patiala', 'Patiala'), ('Bathinda', 'Bathinda'), ('Hoshiarpur', 'Hoshiarpur'), ('Batala', 'Batala'), ('Mohali', 'Mohali'), ('Abohar', 'Abohar'), ('Pathankot', 'Pathankot'), ('Moga', 'Moga'), ('Malerkotla', 'Malerkotla'), ('Khanna', 'Khanna'), ('Muktasar', 'Muktasar'), ('Barnala', 'Barnala'), ('Firozpur', 'Firozpur'), ('Kapurthala', 'Kapurthala'), ('Phagwara', 'Phagwara'), ('Zirakpur', 'Zirakpur'), ('Rajpura', 'Rajpura'))), ('Puducherry', (('Pondicherry', 'Pondicherry'), ('Ozhukarai', 'Ozhukarai'), ('Karaikal', 'Karaikal'))), ('Rajasthan', (('Jaipur', 'Jaipur'), ('Jodhpur', 'Jodhpur'), ('Kota', 'Kota'), ('Bikaner', 'Bikaner'), ('Ajmer', 'Ajmer'), ('Udaipur', 'Udaipur'), ('Bhilwara', 'Bhilwara'), ('Alwar', 'Alwar'), ('Bharatpur', 'Bharatpur'), ('Sri Ganganagar', 'Sri Ganganagar'), ('Sikar', 'Sikar'), ('Pali', 'Pali'), ('Barmer', 'Barmer'), ('Tonk', 'Tonk'), ('Kishangarh', 'Kishangarh'), ('Chittorgarh', 'Chittorgarh'), ('Beawar', 'Beawar'), ('Hanumangarh', 'Hanumangarh'), ('Dholpur', 'Dholpur'), ('Gangapur', 'Gangapur'), ('Sawai Madhopur', 'Sawai Madhopur'), ('Churu', 'Churu'), ('Baran', 'Baran'), ('Makrana', 'Makrana'), ('Nagaur', 'Nagaur'), ('Hindaun', 'Hindaun'), ('Bhiwadi', 'Bhiwadi'), ('Bundi', 'Bundi'), ('Sujangarh', 'Sujangarh'), ('Jhunjhunu', 'Jhunjhunu'), ('Banswara', 'Banswara'), ('Sardarshahar', 'Sardarshahar'), ('Fatehpur', 'Fatehpur'), ('Dausa', 'Dausa'), ('Karauli', 'Karauli'))), ('Sikkim', (('Gangtok', 'Gangtok'),)), ('Telangana', (('Hyderabad', 'Hyderabad'), ('Warangal', 'Warangal'), ('Nizamabad', 'Nizamabad'), ('Karimnagar', 'Karimnagar'), ('Ramagundam', 'Ramagundam'), ('Khammam', 'Khammam'), ('Mahbubnagar', 'Mahbubnagar'), ('Nalgonda', 'Nalgonda'), ('Adilabad', 'Adilabad'), ('Siddipet', 'Siddipet'), ('Suryapet', 'Suryapet'), ('Miryalaguda', 'Miryalaguda'), ('Jagtial', 'Jagtial'), ('Mancherial', 'Mancherial'), ('Kothagudem', 'Kothagudem'))), ('Tamil Nadu', (('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Tirupur', 'Tirupur'), ('Salem', 'Salem'), ('Erode', 'Erode'), ('Tirunelveli', 'Tirunelveli'), ('Vellore', 'Vellore'), ('Tuticorin', 'Tuticorin'), ('Gudiyatham', 'Gudiyatham'), ('Nagercoil', 'Nagercoil'), ('Thanjavur', 'Thanjavur'), ('Dindigul', 'Dindigul'), ('Vaniyambadi', 'Vaniyambadi'), ('Cuddalore', 'Cuddalore'), ('Komarapalayam', 'Komarapalayam'), ('Kanchipuram', 'Kanchipuram'), ('Ambur', 'Ambur'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Pudukkottai', 'Pudukkottai'), ('Kumbakonam', 'Kumbakonam'), ('Rajapalayam', 'Rajapalayam'), ('Hosur', 'Hosur'), ('Karaikudi', 'Karaikudi'), ('Neyveli', 'Neyveli'), ('Nagapattinam', 'Nagapattinam'), ('Viluppuram', 'Viluppuram'), ('Paramakudi', 'Paramakudi'), ('Tiruchengode', 'Tiruchengode'), ('Kovilpatti', 'Kovilpatti'), ('Theni-Allinagaram', 'Theni-Allinagaram'), ('Kadayanallur', 'Kadayanallur'), ('Pollachi', 'Pollachi'), ('Ooty', 'Ooty'))), ('Tripura', (('Agartala', 'Agartala'),)), ('Uttar Pradesh', (('Kanpur', 'Kanpur'), ('Lucknow', 'Lucknow'), ('Ghaziabad', 'Ghaziabad'), ('Agra', 'Agra'), ('Varanasi', 'Varanasi'), ('Meerut', 'Meerut'), ('Allahabad', 'Allahabad'), ('Bareilly', 'Bareilly'), ('Aligarh', 'Aligarh'), ('Moradabad', 'Moradabad'), ('Saharanpur', 'Saharanpur'), ('Gorakhpur', 'Gorakhpur'), ('Faizabad', 'Faizabad'), ('Firozabad', 'Firozabad'), ('Jhansi', 'Jhansi'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Mathura', 'Mathura'), ('Budaun', 'Budaun'), ('Rampur', 'Rampur'), ('Shahjahanpur', 'Shahjahanpur'), ('Farrukhabad', 'Farrukhabad'), ('Mau', 'Mau'), ('Hapur', 'Hapur'), ('Noida', 'Noida'), ('Etawah', 'Etawah'), ('Mirzapur', 'Mirzapur'), ('Bulandshahr', 'Bulandshahr'), ('Sambhal', 'Sambhal'), ('Amroha', 'Amroha'), ('Hardoi', 'Hardoi'), ('Fatehpur', 'Fatehpur'), ('Raebareli', 'Raebareli'), ('Orai', 'Orai'), ('Sitapur', 'Sitapur'), ('Bahraich', 'Bahraich'), ('Modinagar', 'Modinagar'), ('Unnao', 'Unnao'), ('Jaunpur', 'Jaunpur'), ('Lakhimpur', 'Lakhimpur'), ('Hathras', 'Hathras'), ('Banda', 'Banda'), ('Pilibhit', 'Pilibhit'), ('Barabanki', 'Barabanki'), ('Mughalsarai', 'Mughalsarai'), ('Khurja', 'Khurja'), ('Gonda', 'Gonda'), ('Mainpuri', 'Mainpuri'), ('Lalitpur', 'Lalitpur'), ('Etah', 'Etah'), ('Deoria', 'Deoria'), ('Ujhani', 'Ujhani'), ('Ghazipur', 'Ghazipur'), ('Sultanpur', 'Sultanpur'), ('Azamgarh', 'Azamgarh'), ('Bijnor', 'Bijnor'), ('Sahaswan', 'Sahaswan'), ('Basti', 'Basti'), ('Chandausi', 'Chandausi'), ('Akbarpur', 'Akbarpur'), ('Ballia', 'Ballia'), ('Mubarakpur', 'Mubarakpur'), ('Tanda', 'Tanda'), ('Greater Noida', 'Greater Noida'), ('Shikohabad', 'Shikohabad'), ('Shamli', 'Shamli'), ('Baraut', 'Baraut'), ('Khair', 'Khair'), ('Kasganj', 'Kasganj'), ('Auraiya', 'Auraiya'), ('Khatauli', 'Khatauli'), ('Deoband', 'Deoband'), ('Nagina', 'Nagina'), ('Mahoba', 'Mahoba'), ('Muradnagar', 'Muradnagar'), ('Bhadohi', 'Bhadohi'), ('Dadri', 'Dadri'), ('Pratapgarh', 'Pratapgarh'), ('Najibabad', 'Najibabad'))), ('Uttarakhand', (('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Roorkee', 'Roorkee'), ('Haldwani', 'Haldwani'), ('Rudrapur', 'Rudrapur'), ('Kashipur', 'Kashipur'), ('Rishikesh', 'Rishikesh'))), ('West Bengal', (('Kolkata', 'Kolkata'), ('Asansol', 'Asansol'), ('Siliguri', 'Siliguri'), ('Durgapur', 'Durgapur'), ('Bardhaman', 'Bardhaman'), ('Malda', 'Malda'), ('Baharampur', 'Baharampur'), ('Habra', 'Habra'), ('Jalpaiguri', 'Jalpaiguri'), ('Kharagpur', 'Kharagpur'), ('Shantipur', 'Shantipur'), ('Dankuni', 'Dankuni'), ('Dhulian', 'Dhulian'), ('Ranaghat', 'Ranaghat'), ('Haldia', 'Haldia'), ('Raiganj', 'Raiganj'), ('Krishnanagar', 'Krishnanagar'), ('Nabadwip', 'Nabadwip'), ('Midnapore', 'Midnapore'), ('Balurghat', 'Balurghat'), ('Basirhat', 'Basirhat'), ('Bankura', 'Bankura'), ('Chakdaha', 'Chakdaha'), ('Darjeeling', 'Darjeeling'), ('Alipurduar', 'Alipurduar'), ('Purulia', 'Purulia'), ('Jangipur', 'Jangipur'), ('Bangaon', 'Bangaon'), ('Cooch Behar', 'Cooch Behar'), ('Bolpur', 'Bolpur'), ('Kanthi', 'Kanthi')))], max_length=20)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=255, null=True)),
                ('bankname', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('accountholdername', models.CharField(blank=True, max_length=250, null=True)),
                ('accountnumber', models.IntegerField(blank=True, null=True)),
                ('ifc', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Creator_SubscribationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='subplan')),
                ('plan_type', models.CharField(choices=[('Reelcat Exhibit', 'Reelcat Exhibit'), ('Reelcat Basic', 'Reelcat Basic'), ('Reelcat Premium', 'Reelcat Premium')], default='Standard', max_length=50)),
                ('plane_period', models.CharField(choices=[('1 year', '365'), ('1week', '7'), ('One month', '30')], default='One month', max_length=50)),
                ('duration', models.PositiveIntegerField(choices=[(365, 365), (7, 7), (30, 30)], default=7)),
                ('plane_price', models.IntegerField()),
                ('plane_desc1', models.CharField(max_length=100)),
                ('plane_desc2', models.CharField(max_length=100)),
                ('plane_desc3', models.CharField(max_length=100)),
                ('plane_desc4', models.CharField(max_length=100)),
                ('plane_desc5', models.CharField(max_length=100)),
                ('plane_desc6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorAddVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='Creatorvideo')),
                ('videolink', embed_video.fields.EmbedVideoField()),
                ('titel', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Creatorvideo')),
                ('language', models.CharField(max_length=250)),
                ('runTime', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='is_downloaded')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('email', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('expires_in', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creator_subscribationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='Creatorplaylistvideo')),
                ('videolink', embed_video.fields.EmbedVideoField()),
                ('titel', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Creatorplaylistimg')),
                ('language', models.CharField(max_length=250)),
                ('runTime', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creatoraddvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubseriesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playlists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creatoraddvideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCaregory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(null=True, upload_to='Creatorplaylistvideo')),
                ('videolink', embed_video.fields.EmbedVideoField()),
                ('titel', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Creatorplaylistimg')),
                ('language', models.CharField(max_length=250)),
                ('runTime', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('playlists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playlists')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('items',   models.ManyToManyField(to='accounts.SubOrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubseriesSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('items', models.ManyToManyField(to='accounts.SubseriesOrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('items', models.ManyToManyField(to='accounts.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('img', models.ImageField(null=True, upload_to='subs/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.suborderitem')),
            ],
        ),
        migrations.AddField(
            model_name='creatoraddvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videocaregory'),
        ),
        migrations.AddField(
            model_name='creatoraddvideo',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coverphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Creatrcoverphoto')),
                ('is_add', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
