# Generated by Django 3.2.15 on 2022-10-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_downloadvideos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadVideos',
        ),
    ]
