# Generated by Django 3.2.15 on 2022-10-08 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_usersession_user_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='session_maneger',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_acc',
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
