# Generated by Django 3.2.15 on 2022-10-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20221008_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator_subscribationplan',
            name='Gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
