# Generated by Django 3.2.15 on 2022-10-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_orderitem_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
