# Generated by Django 3.2.15 on 2022-10-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_orderitem_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
