# Generated by Django 3.2.15 on 2022-10-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='razorpay_expanse',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
