# Generated by Django 3.2.15 on 2022-10-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_subscription_razorpay_expanse'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
