# Generated by Django 3.2.15 on 2022-10-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_creator_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
